---
title: "Evaluating_a_model"
author: "Laura"
date: "4/21/2021"
output: 
xaringan::moon_reader:
    #lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Evaluating a model:
- Following, we present how the quality of a structural-equation model should be evaluated.
- There are primary quality or evaluation criteria.
- Further, Systematicall application to PLS path models.

# Overview:

- primary quality or evaluation criteria and their systematic application to PLS-path-models 
- evaluation of reflective specified measurement models: application of relevant evaluation criteria and their appropriate evaluation 


---

# Evaluation - in general:
- In the evaluation of PLS pathway models: Starting point: R2 from the regressions of the individual endogenous latent variables of the structural model.
- interpret as in ordinary regressions
- Path values: can also be considered as coefficients of an ordinary (multiple) regression

---


# Evaluation of measurement models

- estimation of model > empirical measured variables to assess the relationship between the indicators and constructs (measurement models) and between the different constructs (structural model)

---

