---
title: "measurement_model"
author: "Laura"
date: "5/12/2021"
output: 
xaringan::moon_reader:
    #lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# The measurment model:

- how to measure the latent variables (constructs)
- formative vs. reflective


???
The measurement model specifies how to measure the latent variables (constructs).
We distinguish two ways to measure latent variables: the formative and reflective measurement. 
---

# The measurement model - formative measurement:

Figure 1.4


???
In this figure, the constructs Y1 and Y2 are based on a formative measurement model. 
The arrows point from the indicator variables (here X1-X3 for Y1 and X4-X6 for Y2) to the constructs. 
This implies a causal and predictive relationship in this direction.

---



# The measurement model - reflective measurement:

Figure 1.4


???
In contrast, Y3 and Y4 are based on a reflective measurement model. 
In reflecive measurement models, the arrows point from the constructs to the indicators.
Thus, the construct causes the measurement of the indicator variables or more specific of their covariance. 

The Figure shows also, that for reflective measurement each indicator has an error term. 
In contrast, formative measurements have no error terms. 
We assume, that formative measurements are without error.

In this example, Y4 is measured with only one item instead of multiple items. 

---