---
title: "structural_model"
author: "Laura"
date: "4/21/2021"
output: 
xaringan::moon_reader:
    #lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# The structural model:

- describes relationship between latent variables
- order and sequence of constructs: based on theory/ experiences and knowledge
- path-models from left to right
-- left: independent variables
-- right: dependent variables
-- left: sequential ahead, influence variables on the right

---

## The structural model 2 - exogeneous vs. endogeneous variables:

- variables can serve as dependent and independent
- latent variables serving only as independent = exogeneous latent variables (Y1 and Y2)
- latent variables serving only as dependent (Y4) or as independent and dependent (Y3) = endogeneous latent variables (Y3)
- each variable, which has only arrows coming from it = exogeneous latent variable
- endogeneous latent variables can have either incoming and outgoing arrows (Y3) or only incoming arrows (Y4)
- exogeneous latent variables have no error terms (because these constructs depict the independent variables explaining the dependent variables in the path-model)

---

