---
title: "SEM-in-R Basics - Bootstrapping PLS"
date: "Last update: `r Sys.setlocale('LC_TIME', 'en_US.UTF-8');toOrdinal::toOrdinalDate(Sys.time())`"
#output:
#  rmdformats::downcute:
#    self_contained: true
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print = "75")
opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
opts_knit$set(width = 75)
source("slides_helper.R")
# change this for every file
associated_file <- "basics/60_bootstrapping-pls"

```


# Video for Bootstrapping PLS Models

> Under construction.

<iframe width="640" height="360" src="https://www.youtube.com/embed/yDCMxkgtOw8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>

# Tutorial in RStudio

> Under construction.


```{r figures, results='asis'}
print_slide_md(associated_file)

```



# Next

Next up is [evaluating your model](basics-70-evaluating-pls.html).
